CREATE SEQUENCE IF NOT EXISTS cities_seq
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT DEFAULT NEXTVAL('cities_seq') PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    country VARCHAR(3) NOT NULL,
    latitude DECIMAL(11, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS customers_seq
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT DEFAULT NEXTVAL('customers_seq') PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    city_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    FOREIGN KEY (city_id) REFERENCES cities(id)
);