INSERT INTO cities (name, country, latitude, longitude, active, created_at, updated_at) VALUES
('Bogotá', 'CO', 4.7110, -74.0721, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Medellín', 'CO', 6.2442, -75.5812, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cali', 'CO', 3.4516, -76.5320, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Barranquilla', 'CO', 10.9685, -74.7813, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cartagena', 'CO', 10.3910, -75.4794, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Madrid', 'ES', 40.4168, -3.7038, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Barcelona', 'ES', 41.3851, 2.1734, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Valencia', 'ES', 39.4699, -0.3763, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sevilla', 'ES', 37.3891, -5.9845, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bilbao', 'ES', 43.2630, -2.9349, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO customers (name, description, city_id, created_at, updated_at, active) VALUES
('Ana Basuras SAS', 'Cliente de ejemplo 1', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE),
('City Basuras', 'Cliente de ejemplo 2', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE);
